### ISSUE TITLE
JTSImageViewControllerBackgroundStyle_ScaledDimmed Doesn't exist in v. 1.4?

### ISSUE THREAD

**Issue by siegesmund** [edekhayser/Timeline#8] opened 2015-02-17 17:45 UTC
Throws an error when JTSImageViewController is installed via CocoaPods.

**Comment by edekhayser** [comment] 2015-02-17 18:08
If you are importing that using CocoaPods, remember to import the module
and not just the file.

**Comment by knikaha** [comment] 2015-02-24 15:11
just upgrade your xcode

**Comment by knikaha** [comment] 2015-02-24 15:12
the issue with imageview button when i tapped in gives me error

**Comment by edekhayser** [comment] 2016-03-01 23:10
I'm closing this because it has to do with a version of a dependency that isn't used in the project, and the issue is over a year old. In the future, I may update the project to use a newer version.

**Closed by edekhayser** 2016-03-01 23:10 UTC
